---
title: "Biostat M232 Final Project"
subtitle: Due Mar 21 @ 11:59PM
author: "Ziheng Zhang_606300061"
date: today
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: false
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
knitr:
  opts_chunk: 
    cache: false    
    echo: true
    fig.align: 'center'
    fig.width: 6
    fig.height: 4
    message: FALSE
execute:
  eval: true    
---

## Basic Setup
```{r}
library(tidyverse)
library(naniar)
library(visdat)
library(ggplot2)
library(mice)
library(gridExtra)
library(MASS)
library(MultiVarMI)
library(tidyverse)
library(jomo)
library(broom)
library(UpSetR)
set.seed(5)

```

## Data Preparation
```{r}
lead <- read.table("lead.txt")
lead[lead == -9] <- NA
col_names <- c("id", "smeltdis", "age_mo", "female", "iqf", "lead72", "lead73", 
               "fst2yrs", "totyrs", "pica", "colic", "clumsy", "irrit", 
               "convulse", "fwtap", "tap", "visreact", "audreact", "hypscore")
colnames(lead) <- col_names

lead$female <- factor(lead$female, levels = c(0,1), labels = c("Male", "Female"))
lead$fst2yrs <- factor(lead$fst2yrs, levels = c(0,1), labels = c("No", "Yes"))
lead$pica <- factor(lead$pica, levels = c(0,1), labels = c("No", "Yes"))
lead$colic <- factor(lead$colic, levels = c(0,1), labels = c("No", "Yes"))
lead$clumsy <- factor(lead$clumsy, levels = c(0,1), labels = c("No", "Yes"))
lead$irrit <- factor(lead$irrit, levels = c(0,1), labels = c("No", "Yes"))
lead$convulse <- factor(lead$convulse, levels = c(0,1), labels = c("No", "Yes"))
lead$hypscore <- factor(lead$hypscore, levels = c(0,1,2,3,4), 
                        labels = c("Never", "Seldom", "Sometimes", "Often", 
                                   "Always"), ordered = TRUE)


lead$smeltdis <- factor(lead$smeltdis, levels = c(1,2,3), 
                        labels = c("0-1 miles", "1-2.5 miles", "2.5-4.1 miles"), 
                        ordered = TRUE)
```


## Missing Data Exploration
```{r}
p <- vis_miss(lead) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, size = 12),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18))
plot(p)
# ggsave("missing_data_plot.png", 
#        p, 
#        width = 12, 
#        height = 9, 
#        dpi = 300,
#        bg = "white")

miss_var_summary(lead)

gg_miss_upset(lead, nsets = 6)


```



## Task 1

```{r,eval=FALSE}
lead <- read.table("lead.txt")
lead[lead == -9] <- NA
col_names <- c("id", "smeltdis", "age_mo", "female", "iqf", "lead72", "lead73", 
               "fst2yrs", "totyrs", "pica", "colic", "clumsy", "irrit", 
               "convulse", "fwtap", "tap", "visreact", "audreact", "hypscore")
colnames(lead) <- col_names

lead_na <- lead[, -c(1,2,3)]
lead_mi <- MI(lead_na, var.types = c("O", "NCT", "NCT", 
                                  "NCT", "O", "NCT", "O", "O", "O", "O", "O",
                                  "NCT", "NCT", "NCT", "NCT", "O"), m = 10)

```

```{r}


lead <- read.table("lead.txt")
lead[lead == -9] <- NA
col_names <- c("id", "smeltdis", "age_mo", "female", "iqf", "lead72", "lead73", 
               "fst2yrs", "totyrs", "pica", "colic", "clumsy", "irrit", 
               "convulse", "fwtap", "tap", "visreact", "audreact", "hypscore")
colnames(lead) <- col_names

Y.con <- lead[, c("id", "age_mo", "iqf", "lead72", "lead73", "totyrs", "fwtap", 
                  "tap", "visreact", "audreact")]
Y.cat <- lead[, c("smeltdis", "female", "fst2yrs", "pica", "colic", "clumsy", 
                  "irrit", "convulse", "hypscore")]
Y.numcat <- matrix(c(3, 2, 2, 2, 2, 2, 2, 2, 4), 1, 9)

lead <- jomo1mix(Y.con, Y.cat, Y.numcat)


```

```{r}
lead$female <- factor(lead$female, levels = c(0,1), labels = c("Male", "Female"))
lead$fst2yrs <- factor(lead$fst2yrs, levels = c(0,1), labels = c("No", "Yes"))
lead$pica <- factor(lead$pica, levels = c(0,1), labels = c("No", "Yes"))
lead$colic <- factor(lead$colic, levels = c(0,1), labels = c("No", "Yes"))
lead$clumsy <- factor(lead$clumsy, levels = c(0,1), labels = c("No", "Yes"))
lead$irrit <- factor(lead$irrit, levels = c(0,1), labels = c("No", "Yes"))
lead$convulse <- factor(lead$convulse, levels = c(0,1), labels = c("No", "Yes"))
lead$hypscore <- factor(lead$hypscore, levels = c(0,1,2,3,4), 
                        labels = c("Never", "Seldom", "Sometimes", "Often", 
                                   "Always"), ordered = TRUE)


lead$smeltdis <- factor(lead$smeltdis, levels = c(1,2,3), 
                        labels = c("0-1 miles", "1-2.5 miles", "2.5-4.1 miles"), 
                        ordered = TRUE)

lead <- lead[, -c(20:21)]

```



```{r}
lead1 <- lead[125:248, ]
lead2 <- lead[249:372, ]
lead3 <- lead[373:496, ]
lead4 <- lead[497:620, ]
lead5 <- lead[621:744, ]
lead <- lead[1:124, ]

plts <- list()

plts[[1]] <- ggplot(data = lead, aes(x = lead72)) +
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Original data") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[2]] <- ggplot(data = lead1, aes(x = lead72)) + 
  geom_histogram() + 
  theme_bw() + 
  labs(title = "First imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[3]] <- ggplot(data = lead2, aes(x = lead72)) + 
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Second imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[4]] <- ggplot(data = lead3, aes(x = lead72)) + 
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Third imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[5]] <- ggplot(data = lead4, aes(x = lead72)) +
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Fourth imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[6]] <- ggplot(data = lead5, aes(x = lead72)) +
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Fifth imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )
  
ggsave("imputation_histograms_task1.png", 
       grid.arrange(grobs = plts, nrow = 2), 
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")
```

```{r}
lead_complete <- lead[125:248, ]

lead_complete <- lead_complete |>
  mutate(lead_exposure = ifelse(lead72 >= 40, "High", "Low")) |>
  mutate(lead_exposure = factor(lead_exposure, levels = c("Low", "High")))

p <- ggplot(lead_complete, aes(x = lead_exposure, y = fwtap, fill = lead_exposure)) +
  geom_violin() +
  theme_minimal() +
  labs(
       x = "Lead Exposure",
       y = "fwtap") +
theme(
    legend.position = "none",                          # 图例在底部
    legend.key.size = unit(0.8, 'cm'),                   # 图例符号大小
    axis.title = element_text(size = 34),                # 坐标轴标题字体大小
    axis.text = element_text(size = 32),                 # 坐标轴标签字体大小
    legend.text = element_text(size = 32),               # 图例字体大小
    legend.title = element_text(size = 34)               # 图例标题字体大小
  )
ggsave("fwtap_ts1.png", 
       p,
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")

p <- ggplot(lead_complete, aes(x = lead_exposure, y = tap, fill = lead_exposure)) +
  geom_violin() +
  theme_minimal() +
  labs(
       x = "Lead Exposure",
       y = "tap")+
theme(
    legend.position = "none",                          # 图例在底部
    legend.key.size = unit(0.8, 'cm'),                   # 图例符号大小
    axis.title = element_text(size = 34),                # 坐标轴标题字体大小
    axis.text = element_text(size = 32),                 # 坐标轴标签字体大小
    legend.text = element_text(size = 32),               # 图例字体大小
    legend.title = element_text(size = 34)               # 图例标题字体大小
  )
ggsave("tap_ts1.png", 
       p,
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")

ggplot(lead_complete, aes(x = lead_exposure, fill = irrit)) +
  geom_bar(position = "fill") +  
  geom_text(stat = "count", aes(label = scales::percent(..count../tapply(..count.., ..x.., sum)[..x..], accuracy = 0.1)), 
            position = position_fill(vjust = 0.5), size = 5) + 
  theme_minimal() +
  labs(title = "Proportion of Irritability by Lead Exposure", 
       x = "Lead Exposure Group", y = "Proportion",
       fill = "Irritability (1=Yes, 0=No)")

p <- ggplot(lead_complete, aes(x = lead_exposure, fill = hypscore)) +
  geom_bar(position = "fill") +  
  geom_text(stat = "count", 
            aes(label = scales::percent(..count../tapply(..count.., ..x.., sum)[..x..], accuracy = 0.1)),
            position = position_fill(vjust = 0.5), size = 10, color = "red") + 
  theme_minimal() +
  labs(
       x = "Lead Exposure", y = "Proportion",
       fill = "hypscore") +
theme(
    legend.position = "bottom",                          # 图例在底部
    legend.key.size = unit(0.8, 'cm'),                   # 图例符号大小
    axis.title = element_text(size = 30),                # 坐标轴标题字体大小
    axis.text = element_text(size = 28),                 # 坐标轴标签字体大小
    legend.text = element_text(size = 26),               # 图例字体大小
    legend.title = element_text(size = 30)               # 图例标题字体大小
  )
ggsave("hys_ts1.png", 
       p,
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")
```

```{r}
lead_mice <- lead[125:744, ] |>
  mutate(lead_exposure = ifelse(lead72 >= 40, "High", "Low"),
         lead_exposure = factor(lead_exposure, levels = c("Low", "High")))

lead_mice$Imputation <- as.factor(lead_mice$Imputation)

lead_list <- split(lead_mice, lead_mice$Imputation)

lm_results <- lapply(lead_list, function(data) {
  lm(fwtap ~ lead_exposure, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

fwtap_marginal <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(p.value)
  )
print(fwtap_marginal)

# lm_results_base <- lapply(lead_list, function(data) {
#   lm(fwtap ~ lead_exposure + colic + convulse + age_mo + female, data = data)
# })
# 
# lm_results_interaction <- lapply(lead_list, function(data) {
#   lm(fwtap ~ lead_exposure * colic + lead_exposure * convulse + lead_exposure * age_mo + lead_exposure * female, data = data)
# })
# 
# anova_results <- lapply(seq_along(lm_results_base), function(i) {
#   anova(lm_results_base[[i]], lm_results_interaction[[i]])
# })

lm_results <- lapply(lead_list, function(data) {
  lm(fwtap ~ lead_exposure + colic + convulse + age_mo + female, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

fwtap_partial <- lm_df |>
  group_by(term) |>
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(p.value)
  )
print(fwtap_partial)


lm_results <- lapply(lead_list, function(data) {
  lm(tap ~ lead_exposure, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

tap_marginal <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(p.value)
  )
print(tap_marginal)


lm_results <- lapply(lead_list, function(data) {
  lm(tap ~ lead_exposure + colic + convulse + age_mo + female, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

tap_partial <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(p.value)
  )
print(tap_partial)

```
```{r}
lm_results <- lapply(lead_list, function(data) {
  glm(irrit ~ lead_exposure, family = "binomial", data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

irrit_marginal <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(p.value)
  )
print(irrit_marginal)

lm_results <- lapply(lead_list, function(data) {
  glm(irrit ~ lead_exposure + colic + convulse +  age_mo + female, 
      family = "binomial", data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

irrit_partial <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(p.value)
  )
print(irrit_partial)


lm_results <- lapply(lead_list, function(data) {
  polr(hypscore ~ lead_exposure, Hess = TRUE, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

hypscore_marginal <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(2 * (1-pt(abs(statistic), df = 119)))
  )
print(hypscore_marginal)


lm_results <- lapply(lead_list, function(data) {
  polr(hypscore ~ lead_exposure + colic + convulse + age_mo + female, 
       Hess = TRUE, data = data)
})
       
lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

hypscore_partial <- lm_df %>%
  group_by(term) %>%
  summarise(
    estimate = mean(estimate),
    std.error = sqrt(mean(std.error^2)),
    p.value = mean(1-pt(abs(statistic), df = 115))
  )
print(hypscore_partial)
exp(hypscore_partial$estimate[9])
```



```{r}
lm_results <- lapply(lead_list, function(data) {
  t.test(fwtap ~ lead_exposure, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

fwtap_test <- lm_df %>%
  summarise(
    p.value = mean(p.value)
  )
print(fwtap_test)

lm_results <- lapply(lead_list, function(data) {
  t.test(tap ~ lead_exposure, data = data)
})

lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

tap_test <- lm_df %>%
  summarise(
    p.value = mean(p.value)
  )
print(tap_test)


# lm_results <- lapply(lead_list, function(data) {
#   chisq.test(table(data$lead_exposure, data$irrit))
# })
# 
# lm_summaries <- lapply(lm_results, tidy) 
# lm_df <- bind_rows(lm_summaries, .id = "Imputation")
# 
# irrit_test <- lm_df %>%
#   summarise(
#     p.value = mean(p.value)
#   )
# print(irrit_test)


lm_results <- lapply(lead_list, function(data) {
  wilcox.test(as.numeric(data$hypscore) ~ data$lead_exposure)
})
lm_summaries <- lapply(lm_results, tidy) 
lm_df <- bind_rows(lm_summaries, .id = "Imputation")

hypscore_test <- lm_df %>%
  summarise(
    p.value = mean(p.value)
  )
print(hypscore_test)

```






## Task 2 -- Mice Imputation


```{r}
lead <- read.table("lead.txt")
lead[lead == -9] <- NA
col_names <- c("id", "smeltdis", "age_mo", "female", "iqf", "lead72", "lead73", 
               "fst2yrs", "totyrs", "pica", "colic", "clumsy", "irrit", 
               "convulse", "fwtap", "tap", "visreact", "audreact", "hypscore")
colnames(lead) <- col_names

lead$female <- factor(lead$female, levels = c(0,1), labels = c("Male", "Female"))
lead$fst2yrs <- factor(lead$fst2yrs, levels = c(0,1), labels = c("No", "Yes"))
lead$pica <- factor(lead$pica, levels = c(0,1), labels = c("No", "Yes"))
lead$colic <- factor(lead$colic, levels = c(0,1), labels = c("No", "Yes"))
lead$clumsy <- factor(lead$clumsy, levels = c(0,1), labels = c("No", "Yes"))
lead$irrit <- factor(lead$irrit, levels = c(0,1), labels = c("No", "Yes"))
lead$convulse <- factor(lead$convulse, levels = c(0,1), labels = c("No", "Yes"))
lead$hypscore <- factor(lead$hypscore, levels = c(0,1,2,3,4), 
                        labels = c("Never", "Seldom", "Sometimes", "Often", 
                                   "Always"), ordered = TRUE)


lead$smeltdis <- factor(lead$smeltdis, levels = c(1,2,3), 
                        labels = c("0-1 miles", "1-2.5 miles", "2.5-4.1 miles"), 
                        ordered = TRUE)
```


```{r}

lead_mice <- mice(lead, m = 5)
lead1 <- complete(lead_mice, 1)
lead2 <- complete(lead_mice, 2)
lead3 <- complete(lead_mice, 3)
lead4 <- complete(lead_mice, 4)
lead5 <- complete(lead_mice, 5)
```

```{r}
plts <- list()

plts[[1]] <- ggplot(data = lead, aes(x = lead72)) +
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Original data") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[2]] <- ggplot(data = lead1, aes(x = lead72)) + 
  geom_histogram() + 
  theme_bw() + 
  labs(title = "First imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[3]] <- ggplot(data = lead2, aes(x = lead72)) + 
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Second imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[4]] <- ggplot(data = lead3, aes(x = lead72)) + 
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Third imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[5]] <- ggplot(data = lead4, aes(x = lead72)) +
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Fourth imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )

plts[[6]] <- ggplot(data = lead5, aes(x = lead72)) +
  geom_histogram() + 
  theme_bw() + 
  labs(title = "Fifth imputation") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)
        )
  
ggsave("imputation_histograms_task2.png", 
       grid.arrange(grobs = plts, nrow = 2), 
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")
```


```{r}
lead_complete <- complete(lead_mice)

lead_complete <- lead_complete |>
  mutate(lead_exposure = ifelse(lead72 >= 40, "High", "Low")) |>
  mutate(lead_exposure = factor(lead_exposure, levels = c("Low", "High")))

p <- ggplot(lead_complete, aes(x = lead_exposure, y = fwtap, fill = lead_exposure)) +
  geom_violin() +
  theme_minimal() +
  labs(
       x = "Lead Exposure",
       y = "fwtap") +
theme(
    legend.position = "none",                          # 图例在底部
    legend.key.size = unit(0.8, 'cm'),                   # 图例符号大小
    axis.title = element_text(size = 34),                # 坐标轴标题字体大小
    axis.text = element_text(size = 32),                 # 坐标轴标签字体大小
    legend.text = element_text(size = 32),               # 图例字体大小
    legend.title = element_text(size = 34)               # 图例标题字体大小
  )
ggsave("fwtap_ts2.png", 
       p,
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")

p <- ggplot(lead_complete, aes(x = lead_exposure, y = tap, fill = lead_exposure)) +
  geom_violin() +
  theme_minimal() +
  labs(
       x = "Lead Exposure",
       y = "tap") +
theme(
    legend.position = "none",                          # 图例在底部
    legend.key.size = unit(0.8, 'cm'),                   # 图例符号大小
    axis.title = element_text(size = 34),                # 坐标轴标题字体大小
    axis.text = element_text(size = 32),                 # 坐标轴标签字体大小
    legend.text = element_text(size = 32),               # 图例字体大小
    legend.title = element_text(size = 34)               # 图例标题字体大小
  )
ggsave("tap_ts2.png", 
       p,
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")

ggplot(lead_complete, aes(x = lead_exposure, fill = irrit)) +
  geom_bar(position = "fill") +  
  geom_text(stat = "count", aes(label = scales::percent(..count../tapply(..count.., ..x.., sum)[..x..], accuracy = 0.1)), 
            position = position_fill(vjust = 0.5), size = 5) + 
  theme_minimal() +
  labs(title = "Proportion of Irritability by Lead Exposure", 
       x = "Lead Exposure Group", y = "Proportion",
       fill = "Irritability (1=Yes, 0=No)")

p <- ggplot(lead_complete, aes(x = lead_exposure, fill = hypscore)) +
  geom_bar(position = "fill") +  
  geom_text(stat = "count", 
            aes(label = scales::percent(..count../tapply(..count.., ..x.., sum)[..x..], accuracy = 0.1)),
            position = position_fill(vjust = 0.5), size = 10, color = "red") + 
  theme_minimal() +
  labs(
       x = "Lead Exposure", y = "Proportion",
       fill = "hypscore") +
theme(
    legend.position = "bottom",                          # 图例在底部
    legend.key.size = unit(0.8, 'cm'),                   # 图例符号大小
    axis.title = element_text(size = 30),                # 坐标轴标题字体大小
    axis.text = element_text(size = 28),                 # 坐标轴标签字体大小
    legend.text = element_text(size = 26),               # 图例字体大小
    legend.title = element_text(size = 30)               # 图例标题字体大小
  )
ggsave("hys_ts2.png", 
       p,
       width = 12, 
       height = 9, 
       dpi = 300,
       bg = "white")
```

```{r}
lead_mice_completed <- complete(lead_mice, "long", include = TRUE) |>  
  mutate(lead_exposure = ifelse(lead72 >= 40, "High", "Low"),
         lead_exposure = factor(lead_exposure, levels = c("Low", "High")))

lead_mice <- as.mids(lead_mice_completed)



fwtap_marginal <- with(lead_mice, lm(fwtap ~ lead_exposure))
summary(pool(fwtap_marginal))

fwtap_partial <- with(lead_mice, lm(fwtap ~ lead_exposure + colic + convulse + 
                                      age_mo + female))
summary(pool(fwtap_partial))



tap_marginal <- with(lead_mice, lm(tap ~ lead_exposure))
summary(pool(tap_marginal))

tap_partial <- with(lead_mice, lm(tap ~ lead_exposure + colic + convulse +
                                    age_mo + female))
summary(pool(tap_partial))
```

```{r}
irrit_marginal <- with(lead_mice, glm(irrit ~ lead_exposure, family = "binomial"))
summary(pool(irrit_marginal))

irrit_partial <- with(lead_mice, glm(irrit ~ lead_exposure + colic + convulse +
                                       age_mo + female, family = "binomial"))
summary(pool(irrit_partial))


hypscore_marginal <- with(lead_mice, polr(hypscore ~ lead_exposure, Hess = TRUE))
summary(pool(hypscore_marginal))


hypscore_partial <- with(lead_mice, polr(hypscore ~ lead_exposure + colic + convulse +
                                          age_mo + female, Hess = TRUE))
summary(pool(hypscore_partial))
exp(pool(hypscore_partial)[,3][1,3])
```

```{r}
fwtap_test <- with(lead_mice, t.test(fwtap ~ lead_exposure))
mean(sapply(fwtap_test$analyses[1:5], function(x) x$p.value))
tap_test <- with(lead_mice, t.test(tap ~ lead_exposure))
mean(sapply(tap_test$analyses[1:5], function(x) x$p.value))
irrit_test <- with(lead_mice, chisq.test(table(lead_exposure, irrit)))

hypscore_test <- with(lead_mice, wilcox.test(as.numeric(hypscore) ~ lead_exposure))
mean(sapply(hypscore_test$analyses[1:5], function(x) x$p.value))
```






## Task 4






